#!/usr/bin/env bash

## wget -qO- https://raw.githubusercontent.com/skulluglify/assign6/main/assign6_install | sudo bash

cd $(dirname $0)

if [ -d build ]; then

  rm -rf build
fi

mkdir -p build

cd build

apt install -y wget unzip postgresql python3-pip

wget -c https://github.com/skulluglify/assign6/archive/refs/heads/main.zip
unzip main.zip
cp -r assign6-main/app /

pip install -r assign6-main/requirements.txt

cat << EOF >/lib/systemd/system/star.service
[Unit]
Description=Running My Projekt

[Service]
ExecStart=sh -c "env POSTGRES_USER=users POSTGRES_PASSWORD=password POSTGRES_HOST=0.0.0.0 POSTGRES_DB=library-db POSTGRES_PORT=5432 python3 -m flask --app /app/app --no-debug run --host 0.0.0.0 --port 5000"

[Install]
WantedBy=default.target
EOF

echo "CREATE USER \"users\" WITH PASSWORD 'password';" | sudo -u postgres psql
echo 'CREATE DATABASE "library-db";' | sudo -u postgres psql
echo 'GRANT ALL PRIVILEGES ON DATABASE "library-db" TO "users";' | sudo -u postgres psql

cat<<<$(cat /etc/postgresql/14/main/postgresql.conf | sed -e 's/localhost/\*/g')>/etc/postgresql/14/main/postgresql.conf
cat<<<$(cat /etc/postgresql/14/main/postgresql.conf | sed -e 's/\#listen_addresses/listen_addresses/g')>/etc/postgresql/14/main/postgresql.conf
 
cat << EOF >>/etc/postgresql/14/main/pg_hba.conf

host    all             all             0.0.0.0/0               md5
host    all             all             ::/0                    md5
EOF

systemctl --system --no-wall --force daemon-reload
systemctl --system --no-wall --force restart postgresql

sleep 2

systemctl --system --no-wall --force enable star
systemctl --system --no-wall --force start star
